In [1]:
import pandas as pd

In [12]:
x_train = pd.read_csv('data/81fdc2af-6811-4089-9054-9d59f417f819_dataset/dataset/x_train.csv', sep=',')
y_train = pd.read_csv('data/81fdc2af-6811-4089-9054-9d59f417f819_dataset/dataset/y_train.csv', sep=',')
x_train.head()

,Id,_STATE,FMONTH,IDATE,IMONTH,IDAY,IYEAR,DISPCODE,SEQNO,_PSU,...,_PAREC1,_PASTAE1,_LMTACT1,_LMTWRK1,_LMTSCL1,_RFSEAT2,_RFSEAT3,_FLSHOT6,_PNEUMO2,_AIDTST3
0,0,53,11,11162015,11,16,2015,1100,2015015629,2015015629,...,1,1,3.0,3.0,4.0,1,1,NaN,NaN,2.0
1,1,33,12,12152015,12,15,2015,1200,2015004387,2015004387,...,9,9,3.0,3.0,4.0,9,9,NaN,NaN,NaN
2,2,20,10,10202015,10,20,2015,1100,2015005638,2015005638,...,4,2,2.0,2.0,3.0,1,1,1.0,2.0,2.0
3,3,42,6,6182015,6,18,2015,1100,2015004694,2015004694,...,2,2,2.0,2.0,3.0,1,1,2.0,2.0,2.0
4,4,24,11,11062015,11,6,2015,1100,2015004673,2015004673,...,9,9,3.0,3.0,4.0,1,1,9.0,9.0,2.0

In [13]:
y_train.head()

   Id  _MICHD
0   0      -1
1   1      -1
2   2      -1
3   3      -1
4   4      -1

In [18]:
df = x_train.merge(y_train, on="Id", how="inner")
df.head()

,Id,_STATE,FMONTH,IDATE,IMONTH,IDAY,IYEAR,DISPCODE,SEQNO,_PSU,...,_PASTAE1,_LMTACT1,_LMTWRK1,_LMTSCL1,_RFSEAT2,_RFSEAT3,_FLSHOT6,_PNEUMO2,_AIDTST3,_MICHD
0,0,53,11,11162015,11,16,2015,1100,2015015629,2015015629,...,1,3.0,3.0,4.0,1,1,NaN,NaN,2.0,-1
1,1,33,12,12152015,12,15,2015,1200,2015004387,2015004387,...,9,3.0,3.0,4.0,9,9,NaN,NaN,NaN,-1
2,2,20,10,10202015,10,20,2015,1100,2015005638,2015005638,...,2,2.0,2.0,3.0,1,1,1.0,2.0,2.0,-1
3,3,42,6,6182015,6,18,2015,1100,2015004694,2015004694,...,2,2.0,2.0,3.0,1,1,2.0,2.0,2.0,-1
4,4,24,11,11062015,11,6,2015,1100,2015004673,2015004673,...,9,3.0,3.0,4.0,1,1,9.0,9.0,2.0,-1

In [19]:
df.columns

Index(['Id', '_STATE', 'FMONTH', 'IDATE', 'IMONTH', 'IDAY', 'IYEAR',
       'DISPCODE', 'SEQNO', '_PSU',
       ...
       '_PASTAE1', '_LMTACT1', '_LMTWRK1', '_LMTSCL1', '_RFSEAT2', '_RFSEAT3',
       '_FLSHOT6', '_PNEUMO2', '_AIDTST3', '_MICHD'],
      dtype='object', length=323)

In [21]:
for c in df.columns:
    print(c)

print(len(df.columns))

Id
_STATE
FMONTH
IDATE
IMONTH
IDAY
IYEAR
DISPCODE
SEQNO
_PSU
CTELENUM
PVTRESD1
COLGHOUS
STATERES
CELLFON3
LADULT
NUMADULT
NUMMEN
NUMWOMEN
CTELNUM1
CELLFON2
CADULT
PVTRESD2
CCLGHOUS
CSTATE
LANDLINE
HHADULT
GENHLTH
PHYSHLTH
MENTHLTH
POORHLTH
HLTHPLN1
PERSDOC2
MEDCOST
CHECKUP1
BPHIGH4
BPMEDS
BLOODCHO
CHOLCHK
TOLDHI2
CVDSTRK3
ASTHMA3
ASTHNOW
CHCSCNCR
CHCOCNCR
CHCCOPD1
HAVARTH3
ADDEPEV2
CHCKIDNY
DIABETE3
DIABAGE2
SEX
MARITAL
EDUCA
RENTHOM1
NUMHHOL2
NUMPHON2
CPDEMO1
VETERAN3
EMPLOY1
CHILDREN
INCOME2
INTERNET
WEIGHT2
HEIGHT3
PREGNANT
QLACTLM2
USEEQUIP
BLIND
DECIDE
DIFFWALK
DIFFDRES
DIFFALON
SMOKE100
SMOKDAY2
STOPSMK2
LASTSMK2
USENOW3
ALCDAY5
AVEDRNK2
DRNK3GE5
MAXDRNKS
FRUITJU1
FRUIT1
FVBEANS
FVGREEN
FVORANG
VEGETAB1
EXERANY2
EXRACT11
EXEROFT1
EXERHMM1
EXRACT21
EXEROFT2
EXERHMM2
STRENGTH
LMTJOIN3
ARTHDIS2
ARTHSOCL
JOINPAIN
SEATBELT
FLUSHOT6
FLSHTMY2
IMFVPLAC
PNEUVAC3
HIVTST6
HIVTSTD3
WHRTST10
PDIABTST
PREDIAB1
INSULIN
BLDSUGAR
FEETCHK2
DOCTDIAB
CHKHEMO3
FEETCHK
EYEEXAM
DIABEYE
DIABEDU
CAREGIV1
CRGVREL1
CRGVLNG1
CRGVHRS1
CRGVPRB1
CRGVPERS
CRGVHOUS
CRGVMST2
CRGVEXPT
VIDFCLT2
VIREDIF3
VIPRFVS2
VINOCRE2
VIEYEXM2
VIINSUR2
VICTRCT4
VIGLUMA2
VIMACDG2
CIMEMLOS
CDHOUSE
CDASSIST
CDHELP
CDSOCIAL
CDDISCUS
WTCHSALT
LONGWTCH
DRADVISE
ASTHMAGE
ASATTACK
ASERVIST
ASDRVIST
ASRCHKUP
ASACTLIM
ASYMPTOM
ASNOSLEP
ASTHMED3
ASINHALR
HAREHAB1
STREHAB1
CVDASPRN
ASPUNSAF
RLIVPAIN
RDUCHART
RDUCSTRK
ARTTODAY
ARTHWGT
ARTHEXER
ARTHEDU
TETANUS
HPVADVC2
HPVADSHT
SHINGLE2
HADMAM
HOWLONG
HADPAP2
LASTPAP2
HPVTEST
HPLSTTST
HADHYST2
PROFEXAM
LENGEXAM
BLDSTOOL
LSTBLDS3
HADSIGM3
HADSGCO1
LASTSIG3
PCPSAAD2
PCPSADI1
PCPSARE1
PSATEST1
PSATIME
PCPSARS1
PCPSADE1
PCDMDECN
SCNTMNY1
SCNTMEL1
SCNTPAID
SCNTWRK1
SCNTLPAD
SCNTLWK1
SXORIENT
TRNSGNDR
RCSGENDR
RCSRLTN2
CASTHDX2
CASTHNO2
EMTSUPRT
LSATISFY
ADPLEASR
ADDOWN
ADSLEEP
ADENERGY
ADEAT1
ADFAIL
ADTHINK
ADMOVE
MISTMNT
ADANXEV
QSTVER
QSTLANG
MSCODE
_STSTR
_STRWT
_RAWRAKE
_WT2RAKE
_CHISPNC
_CRACE1
_CPRACE
_CLLCPWT
_DUALUSE
_DUALCOR
_LLCPWT
_RFHLTH
_HCVU651
_RFHYPE5
_CHOLCHK
_RFCHOL
_LTASTH1
_CASTHM1
_ASTHMS1
_DRDXAR1
_PRACE1
_MRACE1
_HISPANC
_RACE
_RACEG21
_RACEGR3
_RACE_G1
_AGEG5YR
_AGE65YR
_AGE80
_AGE_G
HTIN4
HTM4
WTKG3
_BMI5
_BMI5CAT
_RFBMI5
_CHLDCNT
_EDUCAG
_INCOMG
_SMOKER3
_RFSMOK3
DRNKANY5
DROCDY3_
_RFBING5
_DRNKWEK
_RFDRHV5
FTJUDA1_
FRUTDA1_
BEANDAY_
GRENDAY_
ORNGDAY_
VEGEDA1_
_MISFRTN
_MISVEGN
_FRTRESP
_VEGRESP
_FRUTSUM
_VEGESUM
_FRTLT1
_VEGLT1
_FRT16
_VEG23
_FRUITEX
_VEGETEX
_TOTINDA
METVL11_
METVL21_
MAXVO2_
FC60_
ACTIN11_
ACTIN21_
PADUR1_
PADUR2_
PAFREQ1_
PAFREQ2_
_MINAC11
_MINAC21
STRFREQ_
PAMISS1_
PAMIN11_
PAMIN21_
PA1MIN_
PAVIG11_
PAVIG21_
PA1VIGM_
_PACAT1
_PAINDX1
_PA150R2
_PA300R2
_PA30021
_PASTRNG
_PAREC1
_PASTAE1
_LMTACT1
_LMTWRK1
_LMTSCL1
_RFSEAT2
_RFSEAT3
_FLSHOT6
_PNEUMO2
_AIDTST3
_MICHD
323

In [23]:
label = "_MICHD"
df["target"] = (df[label] == 1).astype(int)
corr = (
    df.
    drop(columns=[label, "Id"], errors="ignore")
    .corr()["target"].drop("target")
)

GENHLTH     0.244269
LADULT      0.232173
CVDASPRN    0.227662
_AGE80      0.224547
_AGEG5YR    0.219007
EMPLOY1     0.207186
_AGE_G      0.206873
BPHIGH4     0.204504
_HCVU651    0.196424
_AGE65YR    0.185245
_RFHLTH     0.171599
_RFHYPE5    0.171319
_DRDXAR1    0.168366
DIABETE3    0.161344
DRADVISE    0.143087
USEEQUIP    0.134772
DIFFWALK    0.134324
HAVARTH3    0.121990
ARTTODAY    0.119826
ASERVIST    0.117878
QLACTLM2    0.114686
CHILDREN    0.114094
TOLDHI2     0.113903
LASTPAP2    0.111703
PCPSADE1    0.110889
_RFCHOL     0.110768
ACTIN11_    0.109304
INTERNET    0.108637
CDASSIST    0.104475
PNEUVAC3    0.103427
Name: target, dtype: float64

In [27]:
for name, value in corr.abs().sort_values(ascending=False).head(100).items():
    print(f"{name:12s} {value:.3f}")

GENHLTH      0.244
LADULT       0.232
CVDASPRN     0.228
_AGE80       0.225
_AGEG5YR     0.219
EMPLOY1      0.207
_AGE_G       0.207
BPHIGH4      0.205
_HCVU651     0.196
_AGE65YR     0.185
_RFHLTH      0.172
_RFHYPE5     0.171
_DRDXAR1     0.168
DIABETE3     0.161
DRADVISE     0.143
USEEQUIP     0.135
DIFFWALK     0.134
HAVARTH3     0.122
ARTTODAY     0.120
ASERVIST     0.118
QLACTLM2     0.115
CHILDREN     0.114
TOLDHI2      0.114
LASTPAP2     0.112
PCPSADE1     0.111
_RFCHOL      0.111
ACTIN11_     0.109
INTERNET     0.109
CDASSIST     0.104
PNEUVAC3     0.103
CVDSTRK3     0.101
ADMOVE       0.098
ASPUNSAF     0.098
PHYSHLTH     0.097
VICTRCT4     0.096
_CHISPNC     0.095
_CHLDCNT     0.094
VETERAN3     0.091
ARTHSOCL     0.091
CDHOUSE      0.090
_LMTSCL1     0.090
INSULIN      0.088
ALCDAY5      0.087
CHCCOPD1     0.085
ASACTLIM     0.085
EDUCA        0.083
BPMEDS       0.082
VIDFCLT2     0.081
QSTVER       0.079
_EDUCAG      0.079
LENGEXAM     0.078
SMOKE100     0.074
ASATTACK     0.074
WTCHSALT     0.073
ASINHALR     0.073
CHOLCHK      0.071
SEX          0.071
CDSOCIAL     0.069
HADHYST2     0.068
DIFFALON     0.068
ASTHMED3     0.068
ASTHMAGE     0.067
VIREDIF3     0.067
ASYMPTOM     0.067
NUMWOMEN     0.067
STRENGTH     0.066
_LMTACT1     0.065
PSATIME      0.065
CADULT       0.064
PA1VIGM_     0.062
_BMI5CAT     0.062
NUMADULT     0.061
PREDIAB1     0.061
LMTJOIN3     0.061
HPLSTTST     0.060
CHCOCNCR     0.060
DIFFDRES     0.058
RDUCHART     0.058
HADMAM       0.057
CHCSCNCR     0.057
ADENERGY     0.057
SCNTMEL1     0.057
POORHLTH     0.056
SCNTPAID     0.056
_BMI5        0.054
BLDSUGAR     0.054
FLUSHOT6     0.053
WTKG3        0.053
SCNTLWK1     0.053
RLIVPAIN     0.053
PAVIG11_     0.053
CHECKUP1     0.052
DRNK3GE5     0.052
_INCOMG      0.052
_CHOLCHK     0.052
ADDOWN       0.051
ASDRVIST     0.051
BLOODCHO     0.051
SEQNO        0.050
_PSU         0.050

In [31]:
print(df.isna().sum().sort_values(ascending=False).head(100))

LADULT      328103
COLGHOUS    328103
PCDMDECN    327956
ASDRVIST    327907
ASERVIST    327907
             ...
HADSGCO1    298973
TETANUS     298044
DRADVISE    297543
WTCHSALT    297518
CASTHDX2    289046
Length: 100, dtype: int64